### PR TITLE
flake: overlay: move packages to `hyprland-plugins` namespace

### PR DESCRIPTION
**Pull request by spikespaz**
@fufexan

This will break everybody but there are few who use overlays.

### CODE REVIEW

**Review by fufexan — COMMENTED** [review]
How about we add these packages to Nixpkgs' `hyprlandPlugins` scope?

**Comment by spikespaz** [comment]
My bad. I didn't even see `hyprlandPlugins` but did look for `hyprland-plugins`. I guess I'm allergic (or blind to) `pascalCase`.

**Comment by fufexan** [comment]
I have some news for you...

Anyway I don't think I've seen a scope in Nixpkgs that isn't pascalCase.

**Comment by spikespaz** [comment]
ready I think

**Review by fufexan — APPROVED** [review]
LGTM

**Pull request merged**
