### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rscottyy**
#30

### CODE REVIEW

**Review by vaxerski — CHANGES_REQUESTED** [review]
rather than unsupported, I'd rather just state the quirk.

**Comment by rscottyy** [comment]
What is the quirk? is it csgo related or wayland/xwayland related?

**Comment by vaxerski** [comment]
csgo, the quirk being the shift+tab overlay's mouse being off

**Comment by vaxerski** [comment]
seems to work, yes

**Comment by rscottyy** [comment]
Has something to do with libcef then (Chromium Embedded Framework) which is not a csgo bug, seems more of a steam issue. I will put together an issue to find the root cause. libcef doesn't seem to have issues on xorg AFAIK.

**Pull request closed without merging**
