### PR TITLE
hyprpm: add pin for 0.44.0

### PR DESCRIPTION
**Pull request by x70b1**
We need also a new tag for that version.

### CODE REVIEW

**Comment by vaxerski** [comment]
mb forgor

**Comment by x70b1** [comment]
Cool! 
Could you add the v0.44.0 tag? Then we are done here.

**Comment by vaxerski** [comment]
?

**Comment by x70b1** [comment]
https://github.com/hyprwm/hyprland-plugins/tags

**Comment by vaxerski** [comment]
oh, I've never done them. @fufexan does them

**Comment by fufexan** [comment]
Added the tag.

**Pull request merged**
